language: python
python:
  - "2.6"
install:
  - true
script:
  - python setup.py install && tests/test_bpgsql.py --dsn 'host=localhost port=5432 user=postgres'

addons:
  postgresql: "9.3"

services:
  - postgresql
