language: python
python:
  - "2.6"
  - "2.7"
# testing with coverage is broken:
#  - "3.2"  # https://travis-ci.org/d33tah/py-bpgsql/jobs/88710167
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

install:
  - true
script:
  - python setup.py install && coverage run tests/test_bpgsql.py --dsn 'host=localhost port=5432 user=postgres'

addons:
  postgresql: "9.3"

services:
  - postgresql

before_install:
  - pip install codecov
after_success:
  - codecov
