language: python
python:
  - "2.6"
install:
  - true
script:
  - python setup.py install && coverage run tests/test_bpgsql.py --dsn 'host=localhost port=5432 user=postgres'

addons:
  postgresql: "9.3"

services:
  - postgresql

before_install:
  - pip install codecov
after_success:
  - codecov
